[package]
name = "rust-solana-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = "0.43.0"
clap = "2.33.3"
serde = "1.0.136"
shell_command = "0.1.0"
